#==========================================#
#=============== Hystrix settings =========#
#==========================================#
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#==========================================#
#============ Eureka settings   ===========#
#==========================================#
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
endpoints:
  shutdown:
    enabled: true
    sensitive: false
ribbon:
  ServerListRefreshInterval: 5000

#==========================================#
#========== Security settings   ===========#
#==========================================#
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://auth-service:5000/uaa/users/current

#==========================================#
#============= MQ settings   ==============#
#==========================================#
#spring:
#  rabbitmq:
#    host: rabbitmq