#==========================================#
#============= Log settings ===============#
#==========================================#
logging:
  config: classpath:config/logging-config.xml
  file: ./logs/${spring.application.name}.log

#==========================================#
#============ Hystrix settings ============#
#==========================================#
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

#==========================================#
#============ Eureka settings   ===========#
#==========================================#
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registryFetchIntervalSeconds: 5
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
endpoints:
  shutdown:
    enabled: true
    sensitive: false
ribbon:
  ServerListRefreshInterval: 5000

#==========================================#
#========== Security settings   ===========#
#==========================================#
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://auth-service:5000/uaa/users/current

#==========================================#
#=========== file settings   ==============#
#==========================================#
file:
  root: /Users/Gavin/Documents/tmp/upload

#==========================================#
#=========== Spring settings   ============#
#==========================================#
spring:
  freemarker:
    checkTemplateLocation: false

#==========================================#
#============ spring web   ================#
#==========================================#
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 1000Mb

#==========================================#
#============== MQ client   ===============#
#==========================================#
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest