name: client

#==========================================#
#=============== Log settings =============#
#==========================================#
logging:
  config: classpath:config/logging-config.xml
  file: ./logs/client.log
  level: debug

#==========================================#
#============ spring settings =============#
#==========================================#
server:
  port: 8081
spring:
  freemarker:
    checkTemplateLocation: false